services:
    db:
        image: postgres
        container_name: ong-finder-database
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: ongfinder
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

networks:
    default:
        name: ong-finder
        external: true
